# Generated by Django 3.0.6 on 2020-05-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flight',
        ),
    ]
